---
- include_tasks: setup-docker.yml

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: docker_restart_on_package_change

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
