---

- name: install dependent packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - alien
    - libaio1
    - unixodbc
    - bc

- name: check if the deb package exists
  stat:
    path: /tmp/oracle-xe*.deb
  register: deb_package

- name: debug
  debug:
    msg: "{{ deb_package }}"

- name: oracle-xe-11 rpm to debian
  shell: "alien --to-deb --scripts {{oracle_rpm_file_name}}"
  args:
    chdir: /tmp
  when: deb_package.stat.exists == False
